trigger:
  - "*"

parameters:
  - name: salt
    default: ''
  - name: useWorkspace
    default: false
    type: boolean

variables:
  - template: variables.yml
  - name: saltVar
    ${{ if eq(parameters.salt, '-' ) }}:
      value: ''
    ${{ else }}:
      value: ${{ parameters.salt }}

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: terraform
    steps:
      - template: terraform.yml
        parameters:
          terraformVersion: $(terraformVersion)
          terraformPath: $(terraformPath)
          servicePrinciple: $(servicePrinciple)
          containerName: $(terraformContainerName)
          storageAccountName: $(terraformStorageAccountName)
          workspace: ${{ parameters.salt }}
          useWorkspace: ${{ parameters.useWorkspace }}
          resourceGroupName: $(terraformResourceGroupName)
          env:
            TF_VAR_branch: $(saltVar)
  - job: deploy
    dependsOn: terraform
    variables:
      acrName: $[ dependencies.terraform.outputs['Terraform.acr_name'] ]
      acrUrl: $[ dependencies.terraform.outputs['Terraform.acr_url'] ]
    steps:
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          workingDirectory: demo/message-sender
          azureSubscription: $(servicePrinciple)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az acr login -n $(acrName)
            docker build . -t $(acrUrl)/message-func:latest
            docker push $(acrUrl)/message-func:latest