trigger:
  - "*"

parameters:
  - name: salt
    default: ''
  - name: useWorkspace
    default: false
    type: boolean

variables:
  - template: variables.yml

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: terraform.yml
    parameters:
      terraformVersion: 1.3.6
      terraformPath: terraform
      servicePrinciple: $(servicePrinciple)
      containerName: terraform
      storageAccountName: samobitf
      workspace: ${{ parameters.salt }}
      useWorkspace: ${{ parameters.useWorkspace }}
      resourceGroupName: terraformstate-rg
      env:
        TF_VAR_branch: ${{ parameters.salt }}
